[package]
name = "nodiform"
version = "0.1.10"
edition = "2021"
rust-version = "1.92"
description = "A laboratory for emergent graphs"
repository = "https://github.com/bodee-angus/nodiform"

[dependencies]
eframe = { version = "=0.31.1", default-features = false, features = ["default_fonts", "wgpu", "x11", "wayland", "persistence"] }
bytemuck = { version = "1.21", features = ["derive"] }
pollster = "0.4"
rquickjs = "=0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
rfd = "0.15"

[dev-dependencies]
naga = { version = "24", features = ["wgsl-in"] }

[profile.release]
lto = false
strip = true

[profile.dev]
debug = 0
